import esbuild from "esbuild";
import process from "node:process";

const banner =
  "/*\n" +
  "THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n" +
  "If you want to inspect the source, open the plugin project instead.\n" +
  "*/";

const production = process.argv.includes("--production");

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  banner: {
    js: banner
  },
  outfile: "main.js"
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
