/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to inspect the source, open the plugin project instead.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SetToRootPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");
var ENGLISH = {
  menuSetToRoot: "Set to root",
  viewName: "Set to root",
  emptyTitle: "No root folder set",
  emptyMissingTitle: "The configured root folder is unavailable",
  emptyDescription: 'Right-click a folder in the default file explorer and choose "Set to root".',
  rootUnavailable: "The selected root folder is unavailable.",
  settingsViewModeName: "Rooted view instances",
  settingsViewModeDesc: "Choose whether Set to root reuses one rooted explorer or opens additional ones.",
  settingsViewModeSingle: "Single view",
  settingsViewModeMultiple: "Multiple views",
  settingsViewIconName: "Rooted view icon",
  settingsViewIconDesc: "Choose the icon used by rooted explorer tabs.",
  settingsViewIconChoose: "Choose icon",
  settingsViewIconReset: "Reset",
  settingsViewIconCurrent: "Current icon: {{icon}}",
  settingsViewIconModalPlaceholder: "Search icons",
  settingsViewIconModalEmpty: "No icons found."
};
var CHINESE = {
  menuSetToRoot: "\u8BBE\u7F6E\u4E3A\u6839\u76EE\u5F55",
  viewName: "\u8BBE\u7F6E\u4E3A\u6839\u76EE\u5F55",
  emptyTitle: "\u672A\u8BBE\u7F6E\u6839\u76EE\u5F55",
  emptyMissingTitle: "\u5DF2\u8BBE\u7F6E\u7684\u6839\u76EE\u5F55\u4E0D\u53EF\u7528",
  emptyDescription: "\u8BF7\u5728\u9ED8\u8BA4\u6587\u4EF6\u5217\u8868\u4E2D\u53F3\u952E\u6587\u4EF6\u5939\uFF0C\u7136\u540E\u9009\u62E9\u201C\u8BBE\u7F6E\u4E3A\u6839\u76EE\u5F55\u201D\u3002",
  rootUnavailable: "\u6240\u9009\u6839\u76EE\u5F55\u4E0D\u53EF\u7528\u3002",
  settingsViewModeName: "\u6839\u76EE\u5F55\u89C6\u56FE\u6570\u91CF",
  settingsViewModeDesc: "\u9009\u62E9\u201C\u8BBE\u7F6E\u4E3A\u6839\u76EE\u5F55\u201D\u65F6\uFF0C\u662F\u590D\u7528\u5355\u4E2A rooted \u89C6\u56FE\uFF0C\u8FD8\u662F\u7EE7\u7EED\u6253\u5F00\u591A\u4E2A\u89C6\u56FE\u3002",
  settingsViewModeSingle: "\u53EA\u4FDD\u7559\u4E00\u4E2A\u89C6\u56FE",
  settingsViewModeMultiple: "\u5141\u8BB8\u591A\u4E2A\u89C6\u56FE",
  settingsViewIconName: "\u6839\u76EE\u5F55\u89C6\u56FE\u56FE\u6807",
  settingsViewIconDesc: "\u9009\u62E9 rooted \u89C6\u56FE\u6807\u7B7E\u4F7F\u7528\u7684\u56FE\u6807\u3002",
  settingsViewIconChoose: "\u9009\u62E9\u56FE\u6807",
  settingsViewIconReset: "\u6062\u590D\u9ED8\u8BA4",
  settingsViewIconCurrent: "\u5F53\u524D\u56FE\u6807\uFF1A{{icon}}",
  settingsViewIconModalPlaceholder: "\u641C\u7D22\u56FE\u6807",
  settingsViewIconModalEmpty: "\u6CA1\u6709\u5339\u914D\u7684\u56FE\u6807\u3002"
};
function getTable() {
  return (0, import_obsidian.getLanguage)().toLowerCase().startsWith("zh") ? CHINESE : ENGLISH;
}
function t(key) {
  return getTable()[key];
}
function tf(key, values) {
  let text = t(key);
  for (const [name, value] of Object.entries(values)) {
    text = text.replace(`{{${name}}}`, value);
  }
  return text;
}

// src/rooted-file-explorer.ts
var import_obsidian2 = require("obsidian");
var ROOTED_FILE_EXPLORER_VIEW_TYPE = "set-to-root-explorer";
var FILE_EXPLORER_VIEW_TYPE = "file-explorer";
function createRootedFileExplorerViewWithOptions(app, leaf, options) {
  const creator = getFileExplorerCreator(app);
  if (!creator) {
    return new RootExplorerFallbackView(leaf, options);
  }
  const baseView = creator(leaf);
  return patchExplorerView(baseView, options);
}
function getFileExplorerCreator(app) {
  const registry = app.viewRegistry;
  return registry.getViewCreatorByType?.(FILE_EXPLORER_VIEW_TYPE) ?? null;
}
function patchExplorerView(baseView, options) {
  const view = baseView;
  if (view.rootEmptyStateEl) {
    return view;
  }
  const originalLoad = view.load.bind(view);
  const originalGetState = view.getState.bind(view);
  const originalSetState = view.setState.bind(view);
  const originalGetDisplayText = view.getDisplayText.bind(view);
  const originalSort = view.sort.bind(view);
  const originalRevealInFolder = view.revealInFolder.bind(view);
  const originalHandlePaste = view.handlePaste.bind(view);
  const originalOnRename = view.onRename.bind(view);
  const originalOnDelete = view.onDelete.bind(view);
  initializeEmptyState(view);
  view.icon = options.getIcon();
  view.getViewType = () => ROOTED_FILE_EXPLORER_VIEW_TYPE;
  view.getIcon = () => options.getIcon();
  view.getDisplayText = () => {
    const rootFolder = getRootFolder(view);
    if (rootFolder) {
      return rootFolder.name;
    }
    return view.rootPath ? lastPathSegment(view.rootPath) : originalGetDisplayText();
  };
  view.getState = () => ({
    ...originalGetState(),
    rootPath: view.rootPath
  });
  view.setState = async (state, result) => {
    const nextState = normalizeState(state);
    view.rootPath = nextState.rootPath;
    await originalSetState(nextState, result);
    refreshRootPresentation(view, Boolean(view.rootPath));
    refreshLeafHeader(view);
  };
  view.load = () => {
    originalLoad();
    registerRootContextMenuOverride(view);
    refreshRootPresentation(view, false);
  };
  view.sort = () => {
    const rootFolder = getRootFolder(view);
    refreshRootPresentation(view, false);
    if (!rootFolder) {
      renderChildren(view, []);
      return;
    }
    if (!view.ready) {
      originalSort();
      return;
    }
    if (view.containerEl.isShown()) {
      view._sortQueued = false;
      sortNestedFolders(view);
      renderChildren(view, view.getSortedFolderItems(rootFolder));
      if (view.autoRevealFile) {
        view.revealActiveFile();
      }
      return;
    }
    if (!view._sortQueued) {
      view.containerEl.onNodeInserted(() => view.requestSort(), true);
      view._sortQueued = true;
    }
  };
  view.requestSort = (0, import_obsidian2.debounce)(() => {
    view.sort();
  }, 20, true);
  view.revealInFolder = (file) => {
    if (!isInsideRoot(view, file.path)) {
      return;
    }
    originalRevealInFolder(file);
  };
  view.handlePaste = async (event) => {
    const originalFocused = view.tree.focusedItem;
    if (!originalFocused) {
      view.tree.focusedItem = getRootItem(view);
    }
    try {
      await originalHandlePaste(event);
    } finally {
      if (!originalFocused) {
        view.tree.focusedItem = originalFocused;
      }
    }
  };
  view.onCreateNewNoteClick = (event) => {
    event.preventDefault();
    const targetFolder = getPreferredTargetFolder(view);
    if (!targetFolder) {
      new import_obsidian2.Notice(t("rootUnavailable"));
      return;
    }
    void view.createAbstractFile("file", targetFolder, import_obsidian2.Keymap.isModEvent(event));
  };
  view.onCreateNewFolderClick = (event) => {
    event.preventDefault();
    const targetFolder = getPreferredTargetFolder(view);
    if (!targetFolder) {
      new import_obsidian2.Notice(t("rootUnavailable"));
      return;
    }
    void view.createAbstractFile("folder", targetFolder, false);
  };
  view.onRename = (file, oldPath) => {
    originalOnRename(file, oldPath);
    if (!view.rootPath) {
      return;
    }
    if (view.rootPath === oldPath) {
      view.rootPath = file.path;
    } else if (view.rootPath.startsWith(`${oldPath}/`)) {
      view.rootPath = `${file.path}${view.rootPath.slice(oldPath.length)}`;
    } else {
      return;
    }
    refreshRootPresentation(view, true);
  };
  view.onDelete = (file) => {
    originalOnDelete(file);
    if (!view.rootPath) {
      return;
    }
    if (file.path === view.rootPath || view.rootPath.startsWith(`${file.path}/`)) {
      view.rootPath = null;
      refreshRootPresentation(view, true);
    }
  };
  return view;
}
function normalizeState(state) {
  const objectState = state && typeof state === "object" ? { ...state } : {};
  const rootPath = objectState.rootPath;
  objectState.rootPath = typeof rootPath === "string" && rootPath.trim().length > 0 ? rootPath : null;
  return objectState;
}
function initializeEmptyState(view) {
  const emptyState = view.containerEl.createDiv({ cls: "set-to-root-empty-state" });
  const title = emptyState.createDiv({ cls: "set-to-root-empty-title" });
  const description = emptyState.createDiv({ cls: "set-to-root-empty-desc" });
  view.rootPath = null;
  view.rootEmptyStateEl = emptyState;
  view.rootEmptyTitleEl = title;
  view.rootEmptyDescriptionEl = description;
}
function registerRootContextMenuOverride(view) {
  view.registerDomEvent(
    view.navFileContainerEl,
    "contextmenu",
    (event) => {
      const target = event.targetNode ?? event.target;
      if (target !== view.navFileContainerEl) {
        return;
      }
      const rootFolder = getRootFolder(view);
      if (!rootFolder) {
        return;
      }
      event.preventDefault();
      event.stopImmediatePropagation();
      view.tree.clearSelectedDoms();
      view.tree.setFocusedItem(null);
      openRootBlankAreaContextMenu(view, event, rootFolder);
    },
    { capture: true }
  );
}
function openRootBlankAreaContextMenu(view, event, rootFolder) {
  const rootItem = view.fileItems[rootFolder.path];
  if (!rootItem || rootItem.selfEl.isConnected) {
    view.onFileContextMenu(event, rootFolder);
    return;
  }
  delete view.fileItems[rootFolder.path];
  try {
    view.onFileContextMenu(event, rootFolder);
  } finally {
    view.fileItems[rootFolder.path] = rootItem;
  }
}
function refreshRootPresentation(view, saveLayout) {
  const rootFolder = getRootFolder(view);
  const hasRootFolder = Boolean(rootFolder);
  view.navFileContainerEl.toggle(hasRootFolder);
  view.rootEmptyStateEl.toggle(!hasRootFolder);
  view.rootEmptyTitleEl.setText(
    view.rootPath && !hasRootFolder ? t("emptyMissingTitle") : t("emptyTitle")
  );
  view.rootEmptyDescriptionEl.setText(t("emptyDescription"));
  if (saveLayout) {
    void view.app.workspace.requestSaveLayout();
    refreshLeafHeader(view);
    view.requestSort();
  }
}
function sortNestedFolders(view) {
  for (const item of Object.values(view.fileItems)) {
    if (typeof item.sort === "function") {
      item.sort();
    }
  }
}
function renderChildren(view, items) {
  const scrollTop = view.navFileContainerEl.scrollTop;
  view.tree.infinityScroll.rootEl.vChildren.setChildren(items);
  view.navFileContainerEl.scrollTop = scrollTop;
  view.tree.infinityScroll.compute();
}
function refreshLeafHeader(view) {
  const leafWithHeader = view.leaf;
  leafWithHeader.updateHeader?.();
}
function getRootFolder(view) {
  if (!view.rootPath) {
    return null;
  }
  const folder = view.app.vault.getAbstractFileByPath(view.rootPath);
  return folder instanceof import_obsidian2.TFolder ? folder : null;
}
function getRootItem(view) {
  const rootFolder = getRootFolder(view);
  if (!rootFolder) {
    return null;
  }
  return view.fileItems[rootFolder.path] ?? null;
}
function getPreferredTargetFolder(view) {
  const focusedFile = view.tree.focusedItem?.file;
  if (focusedFile instanceof import_obsidian2.TFolder) {
    return focusedFile;
  }
  if (focusedFile instanceof import_obsidian2.TFile) {
    return focusedFile.parent;
  }
  const activeFile = view.app.workspace.getActiveFile();
  if (activeFile && isInsideRoot(view, activeFile.path)) {
    return activeFile.parent;
  }
  return getRootFolder(view);
}
function isInsideRoot(view, path) {
  const rootPath = view.rootPath;
  if (!rootPath) {
    return false;
  }
  return path === rootPath || path.startsWith(`${rootPath}/`);
}
function lastPathSegment(path) {
  const segments = path.split("/");
  return segments[segments.length - 1] || t("viewName");
}
var RootExplorerFallbackView = class extends import_obsidian2.View {
  constructor(leaf, options) {
    super(leaf);
    this.options = options;
    this.rootPath = null;
    this.icon = options.getIcon();
  }
  async onOpen() {
    this.containerEl.empty();
    this.containerEl.createDiv({ cls: "set-to-root-empty-state" }, (container) => {
      container.createDiv({
        cls: "set-to-root-empty-title",
        text: t("emptyMissingTitle")
      });
      container.createDiv({
        cls: "set-to-root-empty-desc",
        text: t("emptyDescription")
      });
    });
  }
  getViewType() {
    return ROOTED_FILE_EXPLORER_VIEW_TYPE;
  }
  getIcon() {
    return this.options.getIcon();
  }
  getDisplayText() {
    return this.rootPath ? lastPathSegment(this.rootPath) : t("viewName");
  }
  getState() {
    return {
      rootPath: this.rootPath
    };
  }
  async setState(state, _result) {
    const nextState = normalizeState(state);
    this.rootPath = nextState.rootPath;
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  viewMode: "multiple",
  viewIcon: "lucide-folder-closed"
};
function normalizeSettings(data) {
  const settings = data && typeof data === "object" ? { ...DEFAULT_SETTINGS, ...data } : DEFAULT_SETTINGS;
  return {
    viewMode: settings.viewMode === "single" ? "single" : "multiple",
    viewIcon: resolveViewIcon(settings.viewIcon)
  };
}
function resolveViewIcon(iconName) {
  const normalized = iconName?.trim();
  if (!normalized) {
    return DEFAULT_SETTINGS.viewIcon;
  }
  return isValidViewIcon(normalized) ? normalized : DEFAULT_SETTINGS.viewIcon;
}
function isValidViewIcon(iconName) {
  return (0, import_obsidian3.getIconIds)().contains(iconName);
}

// src/main.ts
var SetToRootPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      ROOTED_FILE_EXPLORER_VIEW_TYPE,
      (leaf) => createRootedFileExplorerViewWithOptions(this.app, leaf, {
        getIcon: () => this.getRootedViewIcon()
      })
    );
    this.addSettingTab(new SetToRootSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file, source) => {
        if (source !== "file-explorer-context-menu" || !(file instanceof import_obsidian4.TFolder) || file.isRoot()) {
          return;
        }
        menu.addItem(
          (item) => item.setSection("view").setTitle(t("menuSetToRoot")).setIcon("lucide-panel-left-open").onClick(() => {
            void this.openRootedExplorer(file);
          })
        );
      })
    );
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(ROOTED_FILE_EXPLORER_VIEW_TYPE);
  }
  async updateSettings(nextSettings) {
    this.settings = normalizeSettings(nextSettings);
    await this.saveData(this.settings);
    await this.refreshRootedLeaves();
  }
  getRootedViewIcon() {
    return resolveViewIcon(this.settings.viewIcon);
  }
  async openRootedExplorer(folder) {
    const leaf = this.getTargetLeaf();
    await leaf.setViewState({
      type: ROOTED_FILE_EXPLORER_VIEW_TYPE,
      active: true,
      state: {
        rootPath: folder.path
      }
    });
    await this.app.workspace.revealLeaf(leaf);
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    refreshLeafHeader2(leaf);
  }
  async loadSettings() {
    this.settings = normalizeSettings(await this.loadData());
  }
  getTargetLeaf() {
    if (this.settings.viewMode === "single") {
      return this.app.workspace.getLeavesOfType(ROOTED_FILE_EXPLORER_VIEW_TYPE).first() ?? this.createSidebarLeaf(false);
    }
    return this.createSidebarLeaf(true);
  }
  createSidebarLeaf(split) {
    return this.app.workspace.getLeftLeaf(split) ?? this.app.workspace.getRightLeaf(split) ?? this.app.workspace.getLeaf("tab");
  }
  async refreshRootedLeaves() {
    if (this.settings.viewMode === "single") {
      this.enforceSingleRootedLeaf();
    }
    const icon = this.getRootedViewIcon();
    for (const leaf of this.app.workspace.getLeavesOfType(ROOTED_FILE_EXPLORER_VIEW_TYPE)) {
      const view = leaf.view;
      view.icon = icon;
      refreshLeafHeader2(leaf);
    }
  }
  enforceSingleRootedLeaf() {
    const leaves = this.app.workspace.getLeavesOfType(ROOTED_FILE_EXPLORER_VIEW_TYPE);
    if (leaves.length <= 1) {
      return;
    }
    const activeLeaf = this.app.workspace.activeLeaf;
    const keepLeaf = (activeLeaf && leaves.contains(activeLeaf) ? activeLeaf : null) ?? leaves[leaves.length - 1];
    for (const leaf of leaves) {
      if (leaf !== keepLeaf) {
        leaf.detach();
      }
    }
    refreshLeafHeader2(keepLeaf);
    void this.app.workspace.requestSaveLayout();
  }
};
function refreshLeafHeader2(leaf) {
  const leafWithHeader = leaf;
  leafWithHeader.updateHeader?.();
}
var SetToRootSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName(t("settingsViewModeName")).setDesc(t("settingsViewModeDesc")).addDropdown((dropdown) => {
      dropdown.addOption("single", t("settingsViewModeSingle")).addOption("multiple", t("settingsViewModeMultiple")).setValue(this.plugin.settings.viewMode).onChange(async (value) => {
        await this.plugin.updateSettings({
          ...this.plugin.settings,
          viewMode: value === "single" ? "single" : "multiple"
        });
      });
    });
    const iconSetting = new import_obsidian4.Setting(containerEl).setName(t("settingsViewIconName")).setDesc(t("settingsViewIconDesc")).setClass("set-to-root-icon-setting");
    const previewEl = iconSetting.controlEl.createDiv({ cls: "set-to-root-icon-preview" });
    const currentIconEl = iconSetting.infoEl.createDiv({ cls: "set-to-root-setting-feedback" });
    const renderSelectedIcon = (iconName) => {
      const icon = resolveViewIcon(iconName);
      previewEl.empty();
      (0, import_obsidian4.setIcon)(previewEl, icon);
      currentIconEl.setText(tf("settingsViewIconCurrent", { icon }));
    };
    iconSetting.addButton((button) => {
      button.setButtonText(t("settingsViewIconChoose")).onClick(() => {
        new IconPickerModal(this.app, this.plugin.getRootedViewIcon(), async (icon) => {
          await this.plugin.updateSettings({
            ...this.plugin.settings,
            viewIcon: icon
          });
          renderSelectedIcon(icon);
        }).open();
      });
    });
    iconSetting.addButton((button) => {
      button.setButtonText(t("settingsViewIconReset")).onClick(async () => {
        await this.plugin.updateSettings({
          ...this.plugin.settings,
          viewIcon: DEFAULT_SETTINGS.viewIcon
        });
        renderSelectedIcon(DEFAULT_SETTINGS.viewIcon);
      });
    });
    renderSelectedIcon(this.plugin.settings.viewIcon);
  }
};
var IconPickerModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, selectedIcon, onChoose) {
    super(app);
    this.selectedIcon = selectedIcon;
    this.onChoose = onChoose;
    this.icons = (0, import_obsidian4.getIconIds)().slice().sort((left, right) => left.localeCompare(right));
    this.emptyStateText = t("settingsViewIconModalEmpty");
    this.setPlaceholder(t("settingsViewIconModalPlaceholder"));
  }
  getItems() {
    return this.icons;
  }
  getItemText(item) {
    return item;
  }
  renderSuggestion(item, el) {
    const row = el.createDiv({ cls: "set-to-root-icon-suggestion" });
    const iconEl = row.createDiv({ cls: "set-to-root-icon-suggestion-preview" });
    (0, import_obsidian4.setIcon)(iconEl, item.item);
    row.createDiv({
      cls: "set-to-root-icon-suggestion-label",
      text: item.item
    });
    if (item.item === this.selectedIcon) {
      row.addClass("is-selected");
    }
  }
  onChooseItem(item) {
    void this.onChoose(item);
  }
};
